@echo off
cd /d "c:\Sviluppo\Progetti\London"

echo.
echo ========================================
echo        PUBBLICAZIONE LONDON
echo ========================================
echo.

echo [1/4] Aggiorno versione CSS, JS e JSON...
powershell -NoProfile -EncodedCommand CgAkAHYAZQByAHMAaQBvAG4AIAA9ACAARwBlAHQALQBEAGEAdABlACAALQBGAG8AcgBtAGEAdAAgACcAeQB5AHkAeQBNAE0AZABkAEgASABtAG0AcwBzACcACgAKACQAZgBpAGwAZQBzACAAPQAgAEAAKAAKACAAIAAgACAAJwBpAG4AZABlAHgALgBoAHQAbQBsACcACgApACAAKwAgAEAAKABHAGUAdAAtAEMAaABpAGwAZABJAHQAZQBtACAALQBQAGEAdABoACAAJwBqAHMAJwAgAC0ARgBpAGwAdABlAHIAIAAnACoALgBqAHMAJwAgAC0ARgBpAGwAZQAgAHwAIABGAG8AcgBFAGEAYwBoAC0ATwBiAGoAZQBjAHQAIAB7ACAAJABfAC4ARgB1AGwAbABOAGEAbQBlACAAfQApAAoACgBmAG8AcgBlAGEAYwBoACAAKAAkAGYAaQBsAGUAIABpAG4AIAAkAGYAaQBsAGUAcwApACAAewAKACAAIAAgACAAJAB0AGUAeAB0ACAAPQAgAEcAZQB0AC0AQwBvAG4AdABlAG4AdAAgAC0ATABpAHQAZQByAGEAbABQAGEAdABoACAAJABmAGkAbABlACAALQBSAGEAdwAKAAoAIAAgACAAIAAkAHQAZQB4AHQAIAA9ACAAWwByAGUAZwBlAHgAXQA6ADoAUgBlAHAAbABhAGMAZQAoAAoAIAAgACAAIAAgACAAIAAgACQAdABlAHgAdAAsAAoAIAAgACAAIAAgACAAIAAgACcAKAAoAD8AOgBzAHIAYwB8AGgAcgBlAGYAfABmAGUAdABjAGgAXAAoACkAXABzACoAWwAiACcAJwBdACkAKABbAF4AIgAnACcAXQArAFwALgAoAD8AOgBjAHMAcwB8AGoAcwB8AGoAcwBvAG4AKQApACgAPwA6AFwAPwB2AD0AWwBeACIAJwAnAF0AKgApAD8AKABbACIAJwAnAF0AKQAnACwACgAgACAAIAAgACAAIAAgACAAJwAkADEAJAAyAD8AdgA9ACcAIAArACAAJAB2AGUAcgBzAGkAbwBuACAAKwAgACcAJAAzACcALAAKACAAIAAgACAAIAAgACAAIABbAFMAeQBzAHQAZQBtAC4AVABlAHgAdAAuAFIAZQBnAHUAbABhAHIARQB4AHAAcgBlAHMAcwBpAG8AbgBzAC4AUgBlAGcAZQB4AE8AcAB0AGkAbwBuAHMAXQA6ADoASQBnAG4AbwByAGUAQwBhAHMAZQAKACAAIAAgACAAKQAKAAoAIAAgACAAIABTAGUAdAAtAEMAbwBuAHQAZQBuAHQAIAAtAEwAaQB0AGUAcgBhAGwAUABhAHQAaAAgACQAZgBpAGwAZQAgAC0AVgBhAGwAdQBlACAAJAB0AGUAeAB0ACAALQBFAG4AYwBvAGQAaQBuAGcAIAB1AHQAZgA4AAoAfQAKAAoAVwByAGkAdABlAC0ASABvAHMAdAAgACIAVgBlAHIAcwBpAG8AbgBlACAAYwBhAGMAaABlADoAIAAkAHYAZQByAHMAaQBvAG4AIgAKAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAiAEEAZwBnAGkAbwByAG4AYQB0AGkAIAByAGkAZgBlAHIAaQBtAGUAbgB0AGkAIABDAFMAUwAsACAASgBTACAAZQAgAEoAUwBPAE4ALgAiAAoA
if errorlevel 1 (
    echo.
    echo ERRORE durante l'aggiornamento della cache.
    pause
    exit /b 1
)

echo.
echo [2/4] Aggiungo le modifiche...
git add .

echo.
echo [3/4] Creo il commit...
git commit -m "Aggiornamento London"

echo.
echo [4/4] Invio a GitHub...
git push origin main

echo.
echo ========================================
echo        PUBBLICAZIONE COMPLETATA
echo ========================================
echo.
pause
