@echo off
cd /d "c:\Sviluppo\Progetti\London"

echo.
echo ========================================
echo        PUBBLICAZIONE LONDON
echo ========================================
echo.

echo [1/4] Aggiorno la versione cache...
powershell -NoProfile -ExecutionPolicy Bypass -EncodedCommand JAB2AGUAcgBzAGkAbwBuACAAPQAgAEcAZQB0AC0ARABhAHQAZQAgAC0ARgBvAHIAbQBhAHQAIAAnAHkAeQB5AHkATQBNAGQAZABIAEgAbQBtAHMAcwAnAAoACgAkAGYAaQBsAGUAcwAgAD0AIABAACgAJwBpAG4AZABlAHgALgBoAHQAbQBsACcAKQAgACsAIABAACgARwBlAHQALQBDAGgAaQBsAGQASQB0AGUAbQAgAC0AUABhAHQAaAAgACcAagBzACcAIAAtAEYAaQBsAHQAZQByACAAJwAqAC4AagBzACcAIAAtAEYAaQBsAGUAIAB8ACAARgBvAHIARQBhAGMAaAAtAE8AYgBqAGUAYwB0ACAAewAgACQAXwAuAEYAdQBsAGwATgBhAG0AZQAgAH0AKQAKAAoAZgBvAHIAZQBhAGMAaAAgACgAJABmAGkAbABlACAAaQBuACAAJABmAGkAbABlAHMAKQAgAHsACgAgACAAIAAgACQAYgB5AHQAZQBzACAAPQAgAFsAUwB5AHMAdABlAG0ALgBJAE8ALgBGAGkAbABlAF0AOgA6AFIAZQBhAGQAQQBsAGwAQgB5AHQAZQBzACgAJABmAGkAbABlACkACgAgACAAIAAgACQAdABlAHgAdAAgAD0AIABbAFMAeQBzAHQAZQBtAC4AVABlAHgAdAAuAEUAbgBjAG8AZABpAG4AZwBdADoAOgBVAFQARgA4AC4ARwBlAHQAUwB0AHIAaQBuAGcAKAAkAGIAeQB0AGUAcwApAAoACgAgACAAIAAgACQAdABlAHgAdAAgAD0AIABbAHIAZQBnAGUAeABdADoAOgBSAGUAcABsAGEAYwBlACgACgAgACAAIAAgACAAIAAgACAAJAB0AGUAeAB0ACwACgAgACAAIAAgACAAIAAgACAAJwAoACgAPwA6AHMAcgBjAHwAaAByAGUAZgB8AGYAZQB0AGMAaABcACgAKQBcAHMAKgBbACIAJwAnAF0AKQAoAFsAXgAiACcAJwBdACsAXAAuACgAPwA6AGMAcwBzAHwAagBzAHwAagBzAG8AbgApACkAKAA/ADoAXAA/AHYAPQBbAF4AIgAnACcAXQAqACkAPwAoAFsAIgAnACcAXQApACcALAAKACAAIAAgACAAIAAgACAAIAAnACQAMQAkADIAPwB2AD0AJwAgACsAIAAkAHYAZQByAHMAaQBvAG4AIAArACAAJwAkADMAJwAsAAoAIAAgACAAIAAgACAAIAAgAFsAUwB5AHMAdABlAG0ALgBUAGUAeAB0AC4AUgBlAGcAdQBsAGEAcgBFAHgAcAByAGUAcwBzAGkAbwBuAHMALgBSAGUAZwBlAHgATwBwAHQAaQBvAG4AcwBdADoAOgBJAGcAbgBvAHIAZQBDAGEAcwBlAAoAIAAgACAAIAApAAoACgAgACAAIAAgAFsAUwB5AHMAdABlAG0ALgBJAE8ALgBGAGkAbABlAF0AOgA6AFcAcgBpAHQAZQBBAGwAbABUAGUAeAB0ACgACgAgACAAIAAgACAAIAAgACAAJABmAGkAbABlACwACgAgACAAIAAgACAAIAAgACAAJAB0AGUAeAB0ACwACgAgACAAIAAgACAAIAAgACAAWwBTAHkAcwB0AGUAbQAuAFQAZQB4AHQALgBVAFQARgA4AEUAbgBjAG8AZABpAG4AZwBdADoAOgBuAGUAdwAoACQAZgBhAGwAcwBlACkACgAgACAAIAAgACkACgB9AAoACgBXAHIAaQB0AGUALQBIAG8AcwB0ACAAIgBWAGUAcgBzAGkAbwBuAGUAIABjAGEAYwBoAGUAOgAgACQAdgBlAHIAcwBpAG8AbgAiAAoAVwByAGkAdABlAC0ASABvAHMAdAAgACIAUgBpAGYAZQByAGkAbQBlAG4AdABpACAAQwBTAFMALAAgAEoAUwAgAGUAIABKAFMATwBOACAAYQBnAGcAaQBvAHIAbgBhAHQAaQAgAHMAZQBuAHoAYQAgAG0AbwBkAGkAZgBpAGMAYQByAGUAIABsAGEAIABjAG8AZABpAGYAaQBjAGEAIABVAG4AaQBjAG8AZABlAC4AIgAKAA==

if errorlevel 1 (
    echo.
    echo ERRORE durante l'aggiornamento della cache.
    pause
    exit /b 1
)

echo.
echo [2/4] Aggiungo le modifiche...
git add .

echo.
echo [3/4] Creo il commit...
git commit -m "Aggiornamento London"

echo.
echo [4/4] Invio a GitHub...
git push origin main

echo.
echo ========================================
echo        PUBBLICAZIONE COMPLETATA
echo ========================================
echo.
pause
