@echo off
cd /d "c:\Sviluppo\Progetti\London"

echo.
echo ========================================
echo        PUBBLICAZIONE LONDON
echo ========================================
echo.

echo [1/4] Aggiorno la versione di CSS e JS...
powershell -NoProfile -EncodedCommand CgAkAHYAZQByAHMAaQBvAG4AIAA9ACAARwBlAHQALQBEAGEAdABlACAALQBGAG8AcgBtAGEAdAAgACcAeQB5AHkAeQBNAE0AZABkAEgASABtAG0AcwBzACcACgAkAHAAYQB0AGgAIAA9ACAAJwBpAG4AZABlAHgALgBoAHQAbQBsACcACgAkAGgAdABtAGwAIAA9ACAARwBlAHQALQBDAG8AbgB0AGUAbgB0ACAALQBMAGkAdABlAHIAYQBsAFAAYQB0AGgAIAAkAHAAYQB0AGgAIAAtAFIAYQB3AAoACgAkAGgAdABtAGwAIAA9ACAAWwByAGUAZwBlAHgAXQA6ADoAUgBlAHAAbABhAGMAZQAoAAoAIAAgACAAIAAkAGgAdABtAGwALAAKACAAIAAgACAAJwAoACgAPwA6AHMAcgBjAHwAaAByAGUAZgApAD0AIgBbAF4AIgBdACsAXAAuACgAPwA6AGMAcwBzAHwAagBzACkAKQAoAD8AOgBcAD8AdgA9AFsAXgAiAF0AKgApAD8AKAAiACkAJwAsAAoAIAAgACAAIAAnACQAMQA/AHYAPQAnACAAKwAgACQAdgBlAHIAcwBpAG8AbgAgACsAIAAnACQAMgAnACwACgAgACAAIAAgAFsAUwB5AHMAdABlAG0ALgBUAGUAeAB0AC4AUgBlAGcAdQBsAGEAcgBFAHgAcAByAGUAcwBzAGkAbwBuAHMALgBSAGUAZwBlAHgATwBwAHQAaQBvAG4AcwBdADoAOgBJAGcAbgBvAHIAZQBDAGEAcwBlAAoAKQAKAAoAUwBlAHQALQBDAG8AbgB0AGUAbgB0ACAALQBMAGkAdABlAHIAYQBsAFAAYQB0AGgAIAAkAHAAYQB0AGgAIAAtAFYAYQBsAHUAZQAgACQAaAB0AG0AbAAgAC0ARQBuAGMAbwBkAGkAbgBnACAAdQB0AGYAOAAKAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAiAFYAZQByAHMAaQBvAG4AZQAgAEMAUwBTAC8ASgBTADoAIAAkAHYAZQByAHMAaQBvAG4AIgAKAA==
if errorlevel 1 (
    echo.
    echo ERRORE durante l'aggiornamento CSS/JS.
    pause
    exit /b 1
)

echo.
echo [2/4] Aggiungo le modifiche...
git add .

echo.
echo [3/4] Creo il commit...
git commit -m "Aggiornamento London"

echo.
echo [4/4] Invio a GitHub...
git push origin main

echo.
echo ========================================
echo        PUBBLICAZIONE COMPLETATA
echo ========================================
echo.
pause
